### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by movilidadSoporte** [applivery/fastlane-applivery-plugin#5]
When the plugin tries to upload the .ipa to Applivery shows this error:

[17:25:56]: ▸ {"status":false,"error":{"code":400,"msg":"Bad request","field":"slug"}}

The "field" parameter on error sometimes change. In this case is "slug".

**Comment by CesarTrigo** [comment]
Dear @movilidadSoporte, thank you for opening the ticket.
Could you please share the following information that will help us to clarify the problem:
* Applivery Fastlane plugin version (find them [here](https://github.com/applivery/fastlane-applivery-plugin/releases))
* Are you trying to deploy an iOS or Android App?
* Can you please share your fastfile? (Please, do not include your `ACCOUNT API KEY`)

Thank you
