### ISSUE TITLE
Error in build when the commit message starts with "@"

### ISSUE THREAD

**Issue by pedroamador** [applivery/fastlane-applivery-plugin#6]
/var/lib/gems/2.3.0/gems/fastlane-2.56.0/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!': [!] Exit status of command 'curl "https://dashboard.applivery.com/api/builds" -H "Authorization: xxxxxx" -F app="xxxxxx" -F versionName="xxxxx" -F notes="Uploaded automatically with fastlane plugin" -F notify=true -F autoremove=true -F os=android -F tags="" -F deployer=fastlane -F package=@"/myApp/app/build/outputs/apk/app.apk" -F gitBranch="develop" -F gitCommit="xxxxx (FastlaneCore::Interface::FastlaneShellError)
" -F gitMessage="@ie fastlane Staging" -F gitRepositoryURL="xxxx
"' was 26 instead of 0.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (26) couldn't open file "ie fastlane Staging"

**Comment by pedroamador** [comment]
The commit message start exactly with "@ie fastlane xxxxx"

**Comment by Alesete** [comment]
Seems like is not escaping special characters for the git message

@CesarTrigo maybe we should send the message percent encoded?

**Comment by CesarTrigo** [comment]
**Selected for development**
To be done:
- Remove `@` symbol when it appears as the first letter of the value of the following parameters: `gitMessage `, `gitBranch `, `tags`, `notes`, `versionName` before executing `CURL`

**Comment by pedroamador** [comment]
It's the normal behaviour of "curl" when you call it from command line, at least in linux systems where I was tested it. If you run with 

`curl "@test"`

then you get the same result as if you run with

`curl @"test"`

In this example the "curl" command interprets the "test" parameter as a file, whatever you place the "at" symbol within the quotes or before (outside) the quotes.
