### ISSUE TITLE
[Fastlane plugin] Action does not fail if curl command fails

### ISSUE THREAD

**Issue by ndonald2** [applivery/fastlane-applivery-plugin#7]
The way the plugin is currently implemented, the action will not fail if the curl upload command fails. For example, if the build path is invalid and there is no file to upload, the upload API returns a failure code but the action silently ignores it and the lane succeeds. This is not helpful when using the action in CI/CD as it gives a false sense of success; the failure can only be detected by looking into the logs.

**Comment by Alesete** [comment]
Hi @ndonald2 We've just released a new version (v2.1.0) using Faraday instead of curl. Now we are able to manage the Applivery's response and also we are exposing a new SharedValue::APPLIVERY_BUILD_ID

Thanks!

**Comment by CesarTrigo** [comment]
Consider it fixed in [v2.1.0](https://github.com/fastlane-community/fastlane-plugin-applivery/releases/tag/v2.1.0).
